
line_length:
- 300 # warning
- 400 # error

file_length:
- 500 # warning

disabled_rules:
- identifier_name
- trailing_whitespace
- nesting
- discouraged_direct_init
- multiple_closures_with_trailing_closure
- orphaned_doc_comment

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- id
- URL
